### ISSUE TITLE
Dev vs production builds?

### ISSUE THREAD

**Issue by deg** [philoskim/debux#1]
This looks fantastic, thanks!

But, could you add some tips (to the examples or readme) of best practices to pull in this code only in dev builds?

**Comment by philoskim** [comment]
Thanks for your first issue! ^^

As far as I know, there is no way to selectively 'require' another namespace at run-time in ClojureScript.

For example,

```
(ns example.clog
  (:require [debux.cs.core :as d :refer-macros [clog clogn clog clogn break]]))
```

The above cannot be replaced with the following.

```
;; project.clj

    :closure-defines {goog.DEBUG true}} 
```


```
(ns example.clog)

(when js/goog.DEBUG
  (require '[debux.cs.core :as d :refer-macros [clog clogn clog clogn break]]))
```

I want to do what you mentioned, so I will continue to find the way.

If you have any idea, please let me know about it. If so, I will reflect the feature in the next version of debux.

**Comment by deg** [comment]
I don't know any really good answers, sorry!

Perhaps another approach would be to always have the requires, but to have a set of  macros that only expand when js/goog.DEBUG is set.

Also, probably worth asking this question on slack. Wiser minds than mine might have much better answers.

**Comment by deg** [comment]
I found some info that may help you in https://github.com/binaryage/cljs-devtools/blob/master/docs/installation.md#advanced-builds

**Comment by philoskim** [comment]
Now `debux` has a new configuration feature (https://github.com/philoskim/debux#debux-config) for development and the production version `debux-stubs` (https://github.com/philoskim/debux#two-libraries) library. So I close this issue. Thanks a lot for the suggestion!
