### ISSUE TITLE
Use of undeclared Var debux.common.util/clojure

### ISSUE THREAD

**Issue by heyarne** [philoskim/debux#12]
When compiling with shadow-cljs I get the following warning from the Google Closure Compiler:
```
------ WARNING #1 - :undeclared-var --------------------------------------------
 Resource: debux/common/util.cljc:77:14
--------------------------------------------------------------------------------
  74 |   (boolean (:ns env)))
  75 |
  76 | (defn lazy-seq? [coll]
  77 |   (instance? clojure.lang.IPending coll))
--------------------^-----------------------------------------------------------
 Use of undeclared Var debux.common.util/clojure
--------------------------------------------------------------------------------
  78 |
  79 | (defn replace-& [v]
  80 |   (walk/postwalk-replace {'& ''&} v))
  81 |
--------------------------------------------------------------------------------
```
I'm not 100% sure, but the right approach would probably be to check against this, right? https://github.com/clojure/clojurescript/blob/75e4e528f84a38b7bb9741a498f153457182a057/src/main/cljs/cljs/core.cljs#L3412

**Comment by philoskim** [comment]
I deleted the `lazy-seq?` function causing the problem from the source code because it was used in the past but is not used now in the debux code anywhere. So the warning you mentioned will no longer be issued.

Thanks you for the reporting!
