### ISSUE TITLE
:if with nil

### ISSUE THREAD

**Issue by mtruyens** [philoskim/debux#16]
Hi, 

Thanks for your super userful library!

Is it expected behavior that the `... :if nil ...` modifier will always evaluate to true, thereby causing the logging/breaking to effectively occur? I would expect that it should have similar behaviour as `... :if false ...`

**Comment by philoskim** [comment]
Thanks for your bug reporting!

The new 0.6.4 version of debux has just been released.

Thanks again!

**Comment by mtruyens** [comment]
Wow, super fast Sunday service :-) 

Thanks!
