### ISSUE TITLE
Feature request: support for boolean operators

### ISSUE THREAD

**Issue by mtruyens** [philoskim/debux#17]
When debugging, I frequently want to know the evaluation of the individual components of a boolean expression. It would be cool if Debux could support and/or as special macros.

**Comment by philoskim** [comment]
You can use `dbgn` like this.

```
(defn qualified-keyword?
  "Return true if x is a keyword with a namespace"
  [x] (dbgn (and (keyword? x) (namespace x) true)))

(qualified-keyword? :hi/there)
```

```
{:ns examples.dbg, :line 140}
dbgn: (and (keyword? x) (namespace x) true) =>
| x =>
|   :hi/there
| (keyword? x) =>
|   true
| (namespace x) =>
|   "hi"
| (and (keyword? x) (namespace x) true) =>
|   true
```

Do you want to print the result like this?

```
(defn qualified-keyword?
  "Return true if x is a keyword with a namespace"
  [x] (dbg (and (keyword? x) (namespace x) true)))

(qualified-keyword? :hi/there)
```

```
{:ns examples.dbg, :line 140}
dbg: (and (keyword? x) (namespace x) true) =>
| (keyword? x) =>
|   true
| (namespace x) =>
|   "hi"
| (and (keyword? x) (namespace x) true) =>
|   true
```

**Comment by mtruyens** [comment]
IIRC, when I tried a similar example yesterday, the results were difficult to use because of deeply nested forms being printed. 

But I should then look into it again, you have clearly thought about this possibility in your design. Thanks!

**Comment by philoskim** [comment]
I advise you to  use `dbg` inside `dbgn` like this, if you encounter a deeply nested structure.

```
(dbgn (and (dbg (deeply-nested-form ......)) (another-form ...) ...))
``` 

The above `dbg` will prevent `dbgn` from printing `(deeply-nested-form ...)`.

Refer to: https://github.com/philoskim/debux#dbg-inside-dbgn-or-vice-versa
