### ISSUE TITLE
d macro truncates sequences

### ISSUE THREAD

**Issue by danielcompton** [philoskim/debux#4]
```
(count (range 200))
=> 200
(count (debux.dbgn/dbgn (range 200)))
=> 100
```

I think this is because of this line:

https://github.com/philoskim/debux/blob/master/src/debux/dbgn.clj#L218-L219

The limited `result#` should probably be renamed to a different name so that the unchanged result can be passed through safely.

**Comment by philoskim** [comment]
I will correct it in the next version like the following if you this is what you mean. 

```
......
         result# ~form
         result2# (ut/take-n-if-seq n# result#)]
     (when (or dup# (ut/eval-changed? evals# form# result2#))
       (ut/print-form-with-indent (ut/form-header form# msg#)
                                  (:indent-level @ut/config*))
       (ut/pprint-result-with-indent result2# (:indent-level @ut/config*)))
     result#))
......
```

It didn't occured to me before your suggestion. Thank you for good advice!

**Comment by danielcompton** [comment]
Yep that looks good. Thanks!
